version: "3.9"
services:
  nginx-debian:
    build:
      context: ./infrastructure/development/docker/nginx-debian
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/uikit-frontend
    depends_on:
      - node-debian
  node-debian:
    build:
      context: ./infrastructure/development/docker/node-debian
      dockerfile: Dockerfile
    volumes:
      - ./:/uikit-frontend
    command: npm start
    tty: true
  node-debian-cli:
    build:
      context: ./infrastructure/development/docker/node-debian
      dockerfile: Dockerfile
    volumes:
      - ./:/uikit-frontend
